Front end
mdsreq-fga-unb/2022.1-Meio-a-Meio pull request #134
Opened 2022-09-12 19:00 UTC by alcantaragiubs

### Descrição - _Front-end do projeto Galdi_
Parte Finalizada das telas e conexão com o back-end.

### Porque este Pull Request é necessário?
_Finalizar o resto do projeto._

### Critérios de Aceitação
#### Checklist

- [x] Teste passaram
- [x] Build passaram
- [x] Sem conflitos com a Branch Main ou Development.

Resolve #119 .

2022-09-12 22:15 UTC, ciro-c requested changes

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/curso/editar.tsx
> +  console.log(router.query);
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/curso/editar.tsx
> +    console.log("aaaa");
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/curso/editar.tsx
> +      console.log("bbbb");
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/curso/editar.tsx
> +        console.log("ok");
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/curso/editar.tsx
> +        console.log("errado", err);
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/curso/portal.tsx
> +      console.log("erro");
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/disciplina/cadastro.tsx
> +      console.log("erro");
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/disciplina/cadastro.tsx
> +            {/* <Image src= "/images/logo.jpeg" width= '600px' height= '150px'/> */}
retirar comentario

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/disciplina/editar.tsx
> +  console.log(router.query);
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/professor/cadastro.tsx
> +    console.log(e);
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/professor/cadastro.tsx
> +      console.log("bbbb");
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/professor/cadastro.tsx
> +    console.log("aaaa");
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/professor/cadastro.tsx
> +        console.log("ok");
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/professor/cadastro.tsx
> +        console.log("errado", err);
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/professor/cadastro.tsx
> +    console.log(data);
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/professor/cadastro.tsx
> +            {/* <Image src= "/images/logo.jpeg" width= '600px' height= '150px'/> */}
retirar comentario

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/professor/editar.tsx
> +    console.log(e.target.name);
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/professor/editar.tsx
> +    console.log(e);
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/professor/editar.tsx
> +    console.log("aaaa");
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/professor/editar.tsx
> +        console.log("ok");
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/professor/editar.tsx
> +        console.log("errado", err);
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/professor/editar.tsx
> +    console.log(data);
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/professor/portal.tsx
> +      console.log("erro");
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/professor/portal.tsx
> +                  {/* <TableCell align="center">Especialista</TableCell> */}
retirar comentario

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/professor/portal.tsx
> +                    {/* <TableCell align="center">{row.especialista}</TableCell> */}
retirar comentario

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/turma/[detalhes].tsx
> +export async function getServerSideProps({params}){
retirar getserversideprops

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/turma/aluno/cadastro.tsx
> +        console.log(data)
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/turma/aluno/cadastro.tsx
> +        console.log("ok");
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/turma/aluno/cadastro.tsx
> +        console.log(data)
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/turma/aluno/listar.tsx
> +      console.log('erro')
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/turma/aluno/listar.tsx
> +    console.log(router.query.detalhes)
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/turma/aluno/listar.tsx
> +    console.log(idAluno)
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/turma/aluno/listar.tsx
> +      console.log('data: ',data);
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/turma/aluno/listar.tsx
> +      console.log('erro: ', err);
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/turma/atividade/cadastro.tsx
> +    console.log(data);
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/turma/atividade/cadastro.tsx
> +        console.log("ok");
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/turma/atividade/cadastro.tsx
> +        console.log("errado", err);
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/turma/atividade/cadastro.tsx
> +            {/* <Image src= "/images/logo.jpeg" width= '600px' height= '150px'/> */}
retirar comentario

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/turma/atividade/notas/cadastro.tsx
> +        console.log("ok");
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/turma/atividade/notas/cadastro.tsx
> +        console.log("errado", err);
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/turma/atividade/notas/cadastro.tsx
> +            {/* <Image src= "/images/logo.jpeg" width= '600px' height= '150px'/> */}
retirar comentario

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/turma/atividade/notas/listar.tsx
> +    console.log(resNotas.data)
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/turma/cadastro.tsx
> +      console.log("erro");
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/turma/cadastro.tsx
> +    console.log(e);
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/turma/cadastro.tsx
> +    console.log(data);
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/turma/cadastro.tsx
> +        console.log("ok");
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/turma/cadastro.tsx
> +        console.log("errado", err);
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/turma/cadastro.tsx
> +            {/* <Image src= "/images/logo.jpeg" width= '600px' height= '150px'/> */}
retirar comentario

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/turma/diario/cadastro.tsx
> +    console.log(data);
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/turma/diario/cadastro.tsx
> +        console.log("ok");
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/turma/diario/cadastro.tsx
> +        console.log("errado", err);
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/turma/diario/cadastro.tsx
> +    console.log(e);
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/turma/editar.tsx
> +      console.log("erro");
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/turma/editar.tsx
> +    console.log(e);
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/turma/editar.tsx
> +    console.log(data);
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/turma/editar.tsx
> +        console.log("ok");
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/turma/editar.tsx
> +        console.log("errado", err);
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/turma/editar.tsx
> +            {/* <Image src= "/images/logo.jpeg" width= '600px' height= '150px'/> */}
retirar comentario

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/turma/listaPresenca/cadastro.tsx
> +  console.log(router.query.turma_id);
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/turma/listaPresenca/cadastro.tsx
> +    console.log(resAlunosTurma);
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/turma/listaPresenca/cadastro.tsx
> +        console.log("ok");
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/turma/listaPresenca/cadastro.tsx
> +    console.log(jaExiste);
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/turma/listaPresenca/listar.tsx
> +      console.log(router.query.detalhes)
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/turma/listaPresenca/listar.tsx
> +      console.log('llalala: ', presencaTurma)
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/pages/turma/portal.tsx
> +      console.log("erro");
retirar console

2022-09-12 22:15 UTC, ciro-c commented on front-end/tsconfig.json
> +  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", "pages/api/auth/[...nextauth].tsx"],
Por que?

2022-09-12 22:15 UTC, ciro-c commented on package.json
> +    "@mui/lab": "^5.0.0-alpha.98"
apagar arquivo

2022-09-12 22:40 UTC, alcantaragiubs commented on front-end/tsconfig.json
> +  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", "pages/api/auth/[...nextauth].tsx"],
É extra. Vou tirar.

2022-09-13 01:20 UTC, ciro-c requested changes

2022-09-13 01:20 UTC, ciro-c commented on front-end/pages/administrador/cadastro.tsx
> +            {/* <Image src= "/images/logo.jpeg" width= '600px' height= '150px'/> */}
Retirar o comentario

2022-09-13 01:20 UTC, ciro-c commented on front-end/pages/aluno/cadastro.tsx
> +            {/* <Image src= "/images/logo.jpeg" width= '600px' height= '150px'/> */}
Retirar comentario

2022-09-13 02:50 UTC, ciro-c approved these changes

2022-09-13 03:08 UTC, merged