feat(#): Read Turma
mdsreq-fga-unb/2022.1-Meio-a-Meio pull request #47
Opened 2022-08-10 04:55 UTC by samuel-sato

### Descrição - _<O que este Pull Request faz?>_
Pequena descrição sobre o PR, exemplificando quais arquivos foram criados, alterados e o porque de cada criação/alteração.

### Porque este Pull Request é necessário?
Explique porque o PR é necessário, por exemplo:
_Permite que o celular do usuário se conecte com o seu computador pessoal._

### Critérios de Aceitação
#### Checklist

- [x] Teste passaram
- [x] Build passaram
- [x] Sem conflitos com a Branch Main ou Development.

Resolve #Número_da_Issue.

2022-08-11 18:10 UTC, ciro-c requested changes
Por favor colocar a pasta turma no src, ou seja retirar ela de dentro da pasta model

2022-08-11 20:29 UTC, samuel-sato commented
Alterações realizadas

2022-08-11 20:38 UTC, samuel-sato commented
Alterações realizadas!

2022-08-18 16:34 UTC, ciro-c requested changes
Por favor preencher a descrição do pr da maneira correta

2022-08-24 11:17 UTC, ciro-c requested changes
Atualiza com a main por favor

2022-08-30 23:59 UTC, ciro-c approved these changes

2022-08-30 23:59 UTC, merged